# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
dist: xenial

scala:
   - 2.12.8

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - pyrosrppltoo@gmail.com

jdk:
  - openjdk8

script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" && sbt travisCi
